name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install UPX
        run: sudo apt-get install upx
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test go
        run: go version
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE
          token: ${{ secrets.TOKEN_GITHUB }}
